### ISSUE TITLE
Problem about reference color

### ISSUE THREAD

**Issue by mia1024** [ionelmc/sphinx-py3doc-enhanced-theme#12]
I am not really sure if this is a bug, but the color of links genereated by `:ref:` seems to be unaffacted by the `linkcolor` in `html_theme_options`. My operation system is macos 10.12.3.

**Comment by ionelmc** [comment]
Seems to work fine locally, please give a reproducer.

**Comment by ionelmc** [comment]
Eg: 
```
Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search` 
```
with 
```
html_theme_options = {
    'linkcolor': 'red',
}
```
results in 
![image](https://cloud.githubusercontent.com/assets/129501/26633804/50ae9b0a-461d-11e7-8a14-b69f9867f446.png)

**Comment by mia1024** [comment]
I found the problem with my code. The reason for my problem is that they are `visitedlink` even though I rebuild the html entirely and therefore the colors are unaffected by the `linkcolor`.

**Comment by ionelmc** [comment]
Clear your browser history.
