### ISSUE TITLE
Allow a custom favicon

### ISSUE THREAD

**Issue by DanielOaks** [ionelmc/sphinx-py3doc-enhanced-theme#4]
It would be very nice to be able to allow a custom favicon. Possibly by putting a PNG in `_static/favicon.png`?

If need be I could possibly look into this myself, time permitting. Thanks for the awesome theme!

**Comment by ionelmc** [comment]
You can do it by inheriting the theme, I'll add some example to the readme soon.

**Comment by ionelmc** [comment]
There's an example here: https://github.com/ionelmc/sphinx-py3doc-enhanced-theme#custom-favicon
