### ISSUE TITLE
Have a single option to switch to "original" py3 docs style

### ISSUE THREAD

**Issue by ionelmc** [ionelmc/sphinx-py3doc-enhanced-theme#6]
@joelfrederico @DanielOaks Would this be acceptable? Would you ever need to pick individual options?

**Comment by ionelmc** [comment]
I'm thinking about an option `noextras` that will disable all the shadows, different backgrounds, slightly different coloring. This is better than a myriad of hard to remember options. The font options would remain as is.

**Comment by DanielOaks** [comment]
I think that makes sense as well. I'll be busy at work today, but tonight I should be able to switch my PR to using an option like `noextras` or `py3`.

**Comment by joelfrederico** [comment]
Just got this message - I think that makes sense for my use and most others' uses. I did find a bit of a bug, I'll open up another issue. It looks fairly annoying- like it might be a bug upstream of you inherited from classic...
