### ISSUE TITLE
Blue boxes behind Python domain cross-references

### ISSUE THREAD

**Issue by joelfrederico** [ionelmc/sphinx-py3doc-enhanced-theme#7]
This gives inline code a blue box (with extrastyling disabled):

https://github.com/ionelmc/sphinx-py3doc-enhanced-theme/blob/v2.1.0/src/sphinx_py3doc_enhanced_theme/static/pydoctheme.css_t#L315-L320

But it also gives all Python domain cross references a blue box. I think it might stem from the inherited theme. It looks like Python 3 documentation puts their Python domain cross references in a tt tag instead of a code tag. (<tt (stuff)>(stuff)</tt> vs. <code (stuff)>(stuff)</code>)

Cross-referencing: http://sphinx-doc.org/domains.html#cross-referencing-python-objects
Python example: https://docs.python.org/3/library/argparse.html

**Comment by ionelmc** [comment]
Yes, I think the markup that Sphinx outputs changed (Python 3 docs use older version of Sphinx).

**Comment by ionelmc** [comment]
I've added some automated github publishing (from travis), you can see the "bare" version here: http://ionelmc.github.io/sphinx-py3doc-enhanced-theme/bare/

Feel free to make PRs - they are going to be published there (last build overrides everything, don't do anything crazy :grin:)
