### ISSUE TITLE
Footer scrolling problem in mobile

### ISSUE THREAD

**Issue by tubaq** [ionelmc/sphinx-py3doc-enhanced-theme#8]
Hello, I really like this theme.

When testing here, when scrolling down the footer goes up over the text: http://mobiletest.me/iphone_5_emulator/?u=http://python-aspectlib.readthedocs.org/en/latest/testing.html#spy-mock-toolkit-record-mock-decorators

**Comment by ionelmc** [comment]
Seems fine with latest: http://mobiletest.me/iphone_5_emulator/?u=http://ionelmc.github.io/sphinx-py3doc-enhanced-theme/default/

Looks like I need to rebuild the aspectlib docs.

**Comment by ionelmc** [comment]
Ok it still happens, but only on very long navigation.

**Comment by ionelmc** [comment]
Released 2.2.1 on pypi
