### ISSUE TITLE
Avoid !important in CSS

### ISSUE THREAD

**Issue by mgeier** [ionelmc/sphinx-py3doc-enhanced-theme#9]
Do you really need `!important` in your CSS?

I tried [my sphinx extension](https://github.com/mgeier/nbsphinx) with a few random Sphinx themes, and yours screwed up my formatting.

I could of course just use `!important` on all of my styling, but that would be silly, wouldn't it?

If you don't really need it, you should remove `!important`!

**Comment by ionelmc** [comment]
I agree but someone needs to fix those (prolly just replace the selectors with something that takes more precedence). Interested in helping? :grin:

**Comment by mgeier** [comment]
Sorry, I don't really have the time to do that. And probably I don't have the knowledge either.

**Comment by mgeier** [comment]
I've learned a bit about CSS in the last few days, so I thought I'll give it a try: #10

**Comment by ionelmc** [comment]
Released in https://pypi.python.org/pypi/sphinx_py3doc_enhanced_theme/2.3.0

**Comment by mgeier** [comment]
Cool, thanks!

I'm using it here: http://nbsphinx.readthedocs.org/en/py3doc-enhanced-theme/
It works nicely!
